name: Docker Build

on:
  push:
    branches: [ dev, staging, main, 'feature/**' ]
  pull_request:
    branches: [ dev, staging, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false  # 仅构建，不推送到镜像仓库（如需推送可改为true并配置凭证）
        tags: dedupe-app:latest  # 镜像标签
