name: Python Tests

on:
  push:
    branches: [ dev, staging, main, 'feature/**' ]  # 推送这些分支时触发
  pull_request:
    branches: [ dev, staging, main ]  # 向这些分支提PR时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest tests/test_app.py -v  # 执行测试
